"""Column names update

Revision ID: 307c65c72f56
Revises: 01fdc95a0d95
Create Date: 2024-06-02 03:39:21.868411

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '307c65c72f56'
down_revision: Union[str, None] = '01fdc95a0d95'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email_confirmed', sa.Boolean(), nullable=False))
    op.drop_column('users', 'email_verified')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email_verified', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('users', 'email_confirmed')
    # ### end Alembic commands ###
