"""syntax errors

Revision ID: b876f004e8a0
Revises: 82e9a1a70062
Create Date: 2024-06-01 00:55:43.155248

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b876f004e8a0'
down_revision: Union[str, None] = '82e9a1a70062'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('last_login', sa.DateTime(), nullable=True))
    op.drop_column('users', 'last_loggin')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('last_loggin', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('users', 'last_login')
    # ### end Alembic commands ###
